version: "3.8"
services:
  mysqldb:
    image: mariadb:10.8-jammy
    restart: unless-stopped
    container_name: mysql
    env_file: .env
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=haslo
      - MARIADB_ROOT_PASSWORD=haslo
      - MARIADB_DATABASE=test
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      springboot-mysql-net:
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    container_name: backend
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      springboot-mysql-net:

volumes:
  db:
networks:
  springboot-mysql-net: