version: "3.8"
services:
  database:
    image: mariadb:11.2.2-jammy
    restart: unless-stopped
    container_name: mysql
    env_file: .env
    environment:
      - MARIADB_USER=root
      - MARIADB_PASSWORD=haslo
      - MARIADB_ROOT_PASSWORD=haslo
      - MARIADB_DATABASE=komornik
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend-network
  app:
    depends_on:
      - database
    image: janisbe/komornik-app:v1
    restart: on-failure
    container_name: backend
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    platform: linux/arm64v8
    networks:
      - backend-network
  frontend:
    image: janisbe/frontend:v1
    container_name: frontend
    build:
      context: ./NginxDockerfile
    ports:
      - "4200:80"
    depends_on:
      - app
volumes:
  db:
networks:
  backend-network:
    driver: bridge