version: "3.8"
services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    container_name: mysql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      springboot-mysql-net:
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    container_name: backend
    env_file: .env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      springboot-mysql-net:

volumes:
  db:
networks:
  springboot-mysql-net: